// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: calls.sql

package dbgen

import (
	"context"
	"database/sql"
	"time"
)

const acceptDirectCall = `-- name: AcceptDirectCall :one
UPDATE direct_calls
SET status = 'active', answered_at = $3
WHERE id = $1 AND callee_id = $2 AND status = 'ringing'
RETURNING id, room_id, caller_id, callee_id, status, created_at, answered_at, ended_at
`

type AcceptDirectCallParams struct {
	ID         string       `json:"id"`
	CalleeID   string       `json:"callee_id"`
	AnsweredAt sql.NullTime `json:"answered_at"`
}

func (q *Queries) AcceptDirectCall(ctx context.Context, arg AcceptDirectCallParams) (DirectCall, error) {
	row := q.db.QueryRowContext(ctx, acceptDirectCall, arg.ID, arg.CalleeID, arg.AnsweredAt)
	var i DirectCall
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CallerID,
		&i.CalleeID,
		&i.Status,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.EndedAt,
	)
	return i, err
}

const createDirectCall = `-- name: CreateDirectCall :one
INSERT INTO direct_calls (id, room_id, caller_id, callee_id, status, created_at)
VALUES ($1, $2, $3, $4, 'ringing', $5)
RETURNING id, room_id, caller_id, callee_id, status, created_at, answered_at, ended_at
`

type CreateDirectCallParams struct {
	ID        string    `json:"id"`
	RoomID    string    `json:"room_id"`
	CallerID  string    `json:"caller_id"`
	CalleeID  string    `json:"callee_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateDirectCall(ctx context.Context, arg CreateDirectCallParams) (DirectCall, error) {
	row := q.db.QueryRowContext(ctx, createDirectCall,
		arg.ID,
		arg.RoomID,
		arg.CallerID,
		arg.CalleeID,
		arg.CreatedAt,
	)
	var i DirectCall
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CallerID,
		&i.CalleeID,
		&i.Status,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.EndedAt,
	)
	return i, err
}

const declineDirectCall = `-- name: DeclineDirectCall :one
UPDATE direct_calls
SET status = 'declined', ended_at = $3
WHERE id = $1 AND callee_id = $2 AND status = 'ringing'
RETURNING id, room_id, caller_id, callee_id, status, created_at, answered_at, ended_at
`

type DeclineDirectCallParams struct {
	ID       string       `json:"id"`
	CalleeID string       `json:"callee_id"`
	EndedAt  sql.NullTime `json:"ended_at"`
}

func (q *Queries) DeclineDirectCall(ctx context.Context, arg DeclineDirectCallParams) (DirectCall, error) {
	row := q.db.QueryRowContext(ctx, declineDirectCall, arg.ID, arg.CalleeID, arg.EndedAt)
	var i DirectCall
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CallerID,
		&i.CalleeID,
		&i.Status,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.EndedAt,
	)
	return i, err
}

const endDirectCall = `-- name: EndDirectCall :one
UPDATE direct_calls
SET status = 'ended', ended_at = $3
WHERE id = $1 AND (caller_id = $2 OR callee_id = $2) AND status IN ('ringing', 'active')
RETURNING id, room_id, caller_id, callee_id, status, created_at, answered_at, ended_at
`

type EndDirectCallParams struct {
	ID       string       `json:"id"`
	CallerID string       `json:"caller_id"`
	EndedAt  sql.NullTime `json:"ended_at"`
}

func (q *Queries) EndDirectCall(ctx context.Context, arg EndDirectCallParams) (DirectCall, error) {
	row := q.db.QueryRowContext(ctx, endDirectCall, arg.ID, arg.CallerID, arg.EndedAt)
	var i DirectCall
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CallerID,
		&i.CalleeID,
		&i.Status,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.EndedAt,
	)
	return i, err
}

const getCallForParticipant = `-- name: GetCallForParticipant :one
SELECT id, room_id, caller_id, callee_id, status, created_at, answered_at, ended_at FROM direct_calls
WHERE id = $1 AND (caller_id = $2 OR callee_id = $2)
LIMIT 1
`

type GetCallForParticipantParams struct {
	ID       string `json:"id"`
	CallerID string `json:"caller_id"`
}

func (q *Queries) GetCallForParticipant(ctx context.Context, arg GetCallForParticipantParams) (DirectCall, error) {
	row := q.db.QueryRowContext(ctx, getCallForParticipant, arg.ID, arg.CallerID)
	var i DirectCall
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CallerID,
		&i.CalleeID,
		&i.Status,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.EndedAt,
	)
	return i, err
}

const getOpenCallBetween = `-- name: GetOpenCallBetween :one
SELECT id, room_id, caller_id, callee_id, status, created_at, answered_at, ended_at FROM direct_calls
WHERE status IN ('ringing', 'active')
  AND ((caller_id = $1 AND callee_id = $2) OR (caller_id = $2 AND callee_id = $1))
ORDER BY created_at DESC
LIMIT 1
`

type GetOpenCallBetweenParams struct {
	CallerID string `json:"caller_id"`
	CalleeID string `json:"callee_id"`
}

func (q *Queries) GetOpenCallBetween(ctx context.Context, arg GetOpenCallBetweenParams) (DirectCall, error) {
	row := q.db.QueryRowContext(ctx, getOpenCallBetween, arg.CallerID, arg.CalleeID)
	var i DirectCall
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CallerID,
		&i.CalleeID,
		&i.Status,
		&i.CreatedAt,
		&i.AnsweredAt,
		&i.EndedAt,
	)
	return i, err
}

const listOpenCallsForUser = `-- name: ListOpenCallsForUser :many
SELECT
    c.id,
    c.room_id,
    c.caller_id,
    c.callee_id,
    c.status,
    c.created_at,
    c.answered_at,
    c.ended_at,
    r.invite_code,
    u.id AS peer_id,
    u.username AS peer_username,
    u.display_name AS peer_display_name,
    (c.callee_id = $1) AS incoming
FROM direct_calls c
JOIN rooms r ON r.id = c.room_id
JOIN users u ON u.id = CASE WHEN c.caller_id = $1 THEN c.callee_id ELSE c.caller_id END
WHERE (c.caller_id = $1 OR c.callee_id = $1)
  AND c.status IN ('ringing', 'active')
ORDER BY c.created_at DESC
`

type ListOpenCallsForUserRow struct {
	ID              string       `json:"id"`
	RoomID          string       `json:"room_id"`
	CallerID        string       `json:"caller_id"`
	CalleeID        string       `json:"callee_id"`
	Status          string       `json:"status"`
	CreatedAt       time.Time    `json:"created_at"`
	AnsweredAt      sql.NullTime `json:"answered_at"`
	EndedAt         sql.NullTime `json:"ended_at"`
	InviteCode      string       `json:"invite_code"`
	PeerID          string       `json:"peer_id"`
	PeerUsername    string       `json:"peer_username"`
	PeerDisplayName string       `json:"peer_display_name"`
	Incoming        bool         `json:"incoming"`
}

func (q *Queries) ListOpenCallsForUser(ctx context.Context, calleeID string) ([]ListOpenCallsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listOpenCallsForUser, calleeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenCallsForUserRow{}
	for rows.Next() {
		var i ListOpenCallsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.CallerID,
			&i.CalleeID,
			&i.Status,
			&i.CreatedAt,
			&i.AnsweredAt,
			&i.EndedAt,
			&i.InviteCode,
			&i.PeerID,
			&i.PeerUsername,
			&i.PeerDisplayName,
			&i.Incoming,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
