// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: direct_messages.sql

package dbgen

import (
	"context"
	"time"
)

const createDirectMessage = `-- name: CreateDirectMessage :one
INSERT INTO direct_messages (id, sender_id, recipient_id, body, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, sender_id, recipient_id, body, created_at
`

type CreateDirectMessageParams struct {
	ID          string    `json:"id"`
	SenderID    string    `json:"sender_id"`
	RecipientID string    `json:"recipient_id"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateDirectMessage(ctx context.Context, arg CreateDirectMessageParams) (DirectMessage, error) {
	row := q.db.QueryRowContext(ctx, createDirectMessage,
		arg.ID,
		arg.SenderID,
		arg.RecipientID,
		arg.Body,
		arg.CreatedAt,
	)
	var i DirectMessage
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.RecipientID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const listDirectMessages = `-- name: ListDirectMessages :many
SELECT id, sender_id, recipient_id, body, created_at, username, display_name FROM (
    SELECT
        m.id,
        m.sender_id,
        m.recipient_id,
        m.body,
        m.created_at,
        u.username,
        u.display_name
    FROM direct_messages m
    JOIN users u ON u.id = m.sender_id
    WHERE (m.sender_id = $1 AND m.recipient_id = $2)
       OR (m.sender_id = $2 AND m.recipient_id = $1)
    ORDER BY m.created_at DESC, m.id DESC
    LIMIT 100
) recent
ORDER BY recent.created_at, recent.id
`

type ListDirectMessagesParams struct {
	SenderID    string `json:"sender_id"`
	RecipientID string `json:"recipient_id"`
}

type ListDirectMessagesRow struct {
	ID          string    `json:"id"`
	SenderID    string    `json:"sender_id"`
	RecipientID string    `json:"recipient_id"`
	Body        string    `json:"body"`
	CreatedAt   time.Time `json:"created_at"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) ListDirectMessages(ctx context.Context, arg ListDirectMessagesParams) ([]ListDirectMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDirectMessages, arg.SenderID, arg.RecipientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDirectMessagesRow{}
	for rows.Next() {
		var i ListDirectMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.SenderID,
			&i.RecipientID,
			&i.Body,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
