// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: friends.sql

package dbgen

import (
	"context"
	"time"
)

const createFriendRequest = `-- name: CreateFriendRequest :one
INSERT INTO friend_requests (id, sender_id, receiver_id, created_at)
VALUES ($1, $2, $3, $4)
RETURNING id, sender_id, receiver_id, created_at
`

type CreateFriendRequestParams struct {
	ID         string    `json:"id"`
	SenderID   string    `json:"sender_id"`
	ReceiverID string    `json:"receiver_id"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (FriendRequest, error) {
	row := q.db.QueryRowContext(ctx, createFriendRequest,
		arg.ID,
		arg.SenderID,
		arg.ReceiverID,
		arg.CreatedAt,
	)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.CreatedAt,
	)
	return i, err
}

const createFriendship = `-- name: CreateFriendship :exec
INSERT INTO friendships (user_id, friend_id, created_at)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type CreateFriendshipParams struct {
	UserID    string    `json:"user_id"`
	FriendID  string    `json:"friend_id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateFriendship(ctx context.Context, arg CreateFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, createFriendship, arg.UserID, arg.FriendID, arg.CreatedAt)
	return err
}

const deleteFriendRequest = `-- name: DeleteFriendRequest :exec
DELETE FROM friend_requests WHERE id = $1
`

func (q *Queries) DeleteFriendRequest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFriendRequest, id)
	return err
}

const deleteFriendship = `-- name: DeleteFriendship :exec
DELETE FROM friendships
WHERE (user_id = $1 AND friend_id = $2)
   OR (user_id = $2 AND friend_id = $1)
`

type DeleteFriendshipParams struct {
	UserID   string `json:"user_id"`
	FriendID string `json:"friend_id"`
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.ExecContext(ctx, deleteFriendship, arg.UserID, arg.FriendID)
	return err
}

const getFriendRequestBetween = `-- name: GetFriendRequestBetween :one
SELECT id, sender_id, receiver_id, created_at FROM friend_requests
WHERE (sender_id = $1 AND receiver_id = $2)
   OR (sender_id = $2 AND receiver_id = $1)
LIMIT 1
`

type GetFriendRequestBetweenParams struct {
	SenderID   string `json:"sender_id"`
	ReceiverID string `json:"receiver_id"`
}

func (q *Queries) GetFriendRequestBetween(ctx context.Context, arg GetFriendRequestBetweenParams) (FriendRequest, error) {
	row := q.db.QueryRowContext(ctx, getFriendRequestBetween, arg.SenderID, arg.ReceiverID)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.CreatedAt,
	)
	return i, err
}

const getFriendRequestForReceiver = `-- name: GetFriendRequestForReceiver :one
SELECT id, sender_id, receiver_id, created_at FROM friend_requests WHERE id = $1 AND receiver_id = $2 LIMIT 1
`

type GetFriendRequestForReceiverParams struct {
	ID         string `json:"id"`
	ReceiverID string `json:"receiver_id"`
}

func (q *Queries) GetFriendRequestForReceiver(ctx context.Context, arg GetFriendRequestForReceiverParams) (FriendRequest, error) {
	row := q.db.QueryRowContext(ctx, getFriendRequestForReceiver, arg.ID, arg.ReceiverID)
	var i FriendRequest
	err := row.Scan(
		&i.ID,
		&i.SenderID,
		&i.ReceiverID,
		&i.CreatedAt,
	)
	return i, err
}

const isFriend = `-- name: IsFriend :one
SELECT EXISTS (
    SELECT 1 FROM friendships
    WHERE (user_id = $1 AND friend_id = $2)
       OR (user_id = $2 AND friend_id = $1)
) AS is_friend
`

type IsFriendParams struct {
	UserID   string `json:"user_id"`
	FriendID string `json:"friend_id"`
}

func (q *Queries) IsFriend(ctx context.Context, arg IsFriendParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFriend, arg.UserID, arg.FriendID)
	var is_friend bool
	err := row.Scan(&is_friend)
	return is_friend, err
}

const listFriends = `-- name: ListFriends :many
SELECT u.id, u.username, u.display_name, f.created_at
FROM friendships f
JOIN users u ON u.id = CASE WHEN f.user_id = $1 THEN f.friend_id ELSE f.user_id END
WHERE f.user_id = $1 OR f.friend_id = $1
ORDER BY lower(u.display_name), lower(u.username)
`

type ListFriendsRow struct {
	ID          string    `json:"id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListFriends(ctx context.Context, userID string) ([]ListFriendsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFriends, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFriendsRow{}
	for rows.Next() {
		var i ListFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingFriendRequests = `-- name: ListIncomingFriendRequests :many
SELECT fr.id, fr.created_at, u.id AS user_id, u.username, u.display_name
FROM friend_requests fr
JOIN users u ON u.id = fr.sender_id
WHERE fr.receiver_id = $1
ORDER BY fr.created_at DESC
`

type ListIncomingFriendRequestsRow struct {
	ID          string    `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UserID      string    `json:"user_id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) ListIncomingFriendRequests(ctx context.Context, receiverID string) ([]ListIncomingFriendRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIncomingFriendRequests, receiverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingFriendRequestsRow{}
	for rows.Next() {
		var i ListIncomingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingFriendRequests = `-- name: ListOutgoingFriendRequests :many
SELECT fr.id, fr.created_at, u.id AS user_id, u.username, u.display_name
FROM friend_requests fr
JOIN users u ON u.id = fr.receiver_id
WHERE fr.sender_id = $1
ORDER BY fr.created_at DESC
`

type ListOutgoingFriendRequestsRow struct {
	ID          string    `json:"id"`
	CreatedAt   time.Time `json:"created_at"`
	UserID      string    `json:"user_id"`
	Username    string    `json:"username"`
	DisplayName string    `json:"display_name"`
}

func (q *Queries) ListOutgoingFriendRequests(ctx context.Context, senderID string) ([]ListOutgoingFriendRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, listOutgoingFriendRequests, senderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutgoingFriendRequestsRow{}
	for rows.Next() {
		var i ListOutgoingFriendRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.Username,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
